name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore src/LocaleNames.sln

    - name: Build
      run: dotnet build --no-restore src/LocaleNames.sln

    - name: Test
      run: dotnet test src/LocaleNames.Test/LocaleNames.Test.csproj /p:CollectCoverage=true

    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@master
      with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: ${{ github.workspace }}/out/coverage/lcov.info
